# Generated by Django 4.0.6 on 2022-07-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_booker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('start_time', 'end_time')},
        ),
    ]
