# Generated by Django 4.0.6 on 2022-07-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_booker', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecherSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='student_name',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_email',
            field=models.EmailField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('start_time', 'end_time', 'teacher_name')},
        ),
    ]
