# Generated by Django 4.0.6 on 2022-07-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_booker', '0003_techerschedule_rename_email_booking_student_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='student_name',
            new_name='student_full_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='teacher_name',
            new_name='teacher_full_name',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('start_time', 'end_time', 'teacher_full_name')},
        ),
    ]
