# Generated by Django 4.0.6 on 2022-07-29 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class_booker', '0008_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
