# Generated by Django 4.0.6 on 2022-07-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_booker', '0011_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
    ]
